In [ ]:
#referring tutorial by Soumith Chintala
#Deep Learning with PyTorch: A 60 Minute Blitz (https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

In [2]:
import torch
import numpy as np

In [50]:
def get_variable_info(variable):
    print(f"\n--{variable}")
    if type(variable) == torch.Tensor:
        print(f"dtype: {variable.dtype}")
        print(f"shape: {variable.shape}")
    else:
        print(f"type: {type(variable)}")
        print(f"len: {len(variable)}")

In [27]:
data = [[1,2,3],[4,5,6]]
x_data = torch.tensor(data)
get_variable_info(x_data)


--tensor([[1, 2, 3],
        [4, 5, 6]])
dtype: torch.int64
shape: torch.Size([2, 3])


In [28]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
get_variable_info(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
get_variable_info(x_rand)


--tensor([[1, 1, 1],
        [1, 1, 1]])
dtype: torch.int64
shape: torch.Size([2, 3])

--tensor([[0.5562, 0.7529, 0.1084],
        [0.5605, 0.5307, 0.9213]])
dtype: torch.float32
shape: torch.Size([2, 3])


In [29]:
#randoms or constants
shape = (2,3)
random_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
get_variable_info(random_tensor)
get_variable_info(ones_tensor)
get_variable_info(zeros_tensor)


--tensor([[0.6319, 0.7137, 0.4915],
        [0.1430, 0.4199, 0.0435]])
dtype: torch.float32
shape: torch.Size([2, 3])

--tensor([[1., 1., 1.],
        [1., 1., 1.]])
dtype: torch.float32
shape: torch.Size([2, 3])

--tensor([[0., 0., 0.],
        [0., 0., 0.]])
dtype: torch.float32
shape: torch.Size([2, 3])


In [30]:
#tensor attributes
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [41]:
#cuda
print(f"Is CUDA-Enabled GPU available: {torch.cuda.is_available()}")
print(f"Number of CUDA-Enabled GPU's available: {torch.cuda.device_count()}")
for i in range(torch.cuda.device_count()):
    print(f"GPU index: {i} || GPU name: {torch.cuda.get_device_name(i)}")

Is CUDA-Enabled GPU available: True
Number of CUDA-Enabled GPU's available: 1
GPU index: 0 || GPU name: GeForce GTX 1050 Ti


In [44]:
# move tensor to the GPU if available
tensor = torch.ones(4, 4) 
get_variable_info(tensor) #attributes before moving tensor from cpu to gpu

device = 'cuda' if torch.cuda.is_available() else 'cpu' #get device name
tensor = tensor.to(device)
get_variable_info(tensor)  #attributes before moving tensor from cpu to gpu


--tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
dtype: torch.float32
shape: torch.Size([4, 4])

--tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
dtype: torch.float32
shape: torch.Size([4, 4])


In [45]:
#Some Basic Tensor Operations
tensor[:,1] = 0 
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')


In [16]:

t1 = torch.tensor([0,1,0,1,0]) #5x1
print(t1)
t2 = torch.zeros(shape)
print(t2)
t2[0]=t1
t2

tensor([0, 1, 0, 1, 0])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


tensor([[0., 1., 0., 1., 0.],
        [0., 0., 0., 0., 0.]])

In [46]:
#Concat
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]], device='cuda:0')


In [48]:
#Multiplying
get_variable_info(tensor.mul(tensor))
#or
get_variable_info(tensor*tensor)


--tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')
dtype: torch.float32
shape: torch.Size([4, 4])

--tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')
dtype: torch.float32
shape: torch.Size([4, 4])


In [49]:
#matrix multiplication
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='cuda:0')

In [52]:
#In-place operations Operations that have a _ suffix are in-place. For example: x.copy_(y), x.t_(), will change x.
get_variable_info(tensor)
get_variable_info(tensor.add_(5))


--tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')
dtype: torch.float32
shape: torch.Size([4, 4])

--tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]], device='cuda:0')
dtype: torch.float32
shape: torch.Size([4, 4])


In [53]:
#Bridge with NumPy
t = torch.ones(5)
get_variable_info(t)
n = t.numpy() #taking tensor t and converting it into numpy object
get_variable_info(n)


--tensor([1., 1., 1., 1., 1.])
dtype: torch.float32
shape: torch.Size([5])

--[1. 1. 1. 1. 1.]
type: <class 'numpy.ndarray'>
len: 5


In [54]:
t.add_(1) #change in the tensor reflects in the NumPy array.
get_variable_info(t)


--tensor([2., 2., 2., 2., 2.])
dtype: torch.float32
shape: torch.Size([5])


In [55]:
#NumPy array to Tensor
n = np.ones(5)
get_variable_info(n)
t = torch.from_numpy(n)
get_variable_info(t)


--[1. 1. 1. 1. 1.]
type: <class 'numpy.ndarray'>
len: 5

--tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
dtype: torch.float64
shape: torch.Size([5])


In [58]:
np.add(n, 1, out=n) #change in np reflects in t
get_variable_info(t)


--tensor([4., 4., 4., 4., 4.], dtype=torch.float64)
dtype: torch.float64
shape: torch.Size([5])
