In [1]:
#referring tutorial by Soumith Chintala
#Deep Learning with PyTorch: A 60 Minute Blitz 
#A gentle intro to torch.autograd
#https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#sphx-glr-beginner-blitz-autograd-tutorial-py

In [2]:
#Forward Propagation: In forward prop, the NN makes its best guess about the correct output.
#It runs the input data through each of its functions to make this guess.

In [4]:
#Backward Propagation: In backprop,
#the NN adjusts its parameters proportionate to the error in its guess.
#It does this by traversing backwards from the output, collecting the derivatives of
#the error with respect to the parameters of the functions (gradients),
#and optimizing the parameters using gradient descent. 

#chekout https://www.youtube.com/watch?v=tIeHLnjs5U8

In [6]:
import torch
import torchvision

In [91]:
#load resnet18
model = torchvision.models.resnet18(pretrained = True) #pretrained resnet model

In [92]:
#generate random data
data = torch.rand(1,3,64,64) #(no of images, channels, height, widths)
labels = torch.rand(1,1000)

In [93]:
#run data through model and make prediction
prediction = model(data)
prediction.shape

torch.Size([1, 1000])

In [94]:
for param in model.parameters():
    print(param[0][0][0][0])
    break

tensor(-0.0104, grad_fn=<SelectBackward>)


In [95]:
loss = (prediction - labels).sum()

In [96]:
loss.backward() 

In [97]:
for param in model.parameters():
    print(param[0][0][0][0])
    break

tensor(-0.0104, grad_fn=<SelectBackward>)


In [98]:
#next load an optimizer, SGD with learning rate alpha= 0.01 and momentum= 0.9.
#we register all the parameters of the model in the optimizer
optim = torch.optim.SGD(params = model.parameters(), lr = 0.01, momentum = 0.9)

In [99]:
#we call .step() to initiate gradient descent.
#The optimizer adjusts each parameter by its gradient stored in .grad
optim.step() #gradient descent

In [100]:
#Differentiation in Autograd
a = torch.tensor([2.,3.], requires_grad=True)
b = torch.tensor([6.,4.], requires_grad=True)

In [101]:
# create another tensor from a and b, q = 3a^3 - b^2
q = 3*a**3 - b**2

In [102]:
q

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [103]:
external_grad = torch.tensor([1., 1.])
q.backward(gradient=external_grad)

In [111]:
9*a**2 == a.grad

tensor([True, True])

In [112]:
-2*b == b.grad

tensor([True, True])